"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Base from "../components/base/base";
import ReactQueryProvider from "@/app/components/react-query-provider/react-query-provider";
import { Providers } from "@/redux/provider";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "de" }];
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReactQueryProvider>
            <Providers>
              <Base>{children}</Base>
            </Providers>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
